# Generated by Django 4.0.4 on 2022-06-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogdanzaalas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rutas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rutaclase', models.CharField(max_length=80)),
                ('rutaprofesores', models.CharField(max_length=80)),
            ],
        ),
    ]
