# Generated by Django 4.0.4 on 2022-06-24 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogdanzaalas', '0002_rutas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('fechacoment', models.DateField()),
                ('comentario', models.CharField(max_length=600)),
            ],
        ),
    ]
