from unicodedata import name
from django.contrib import admin
from django.urls import path,include
from.import views

urlpatterns = [
    path('coment',views.coment,name='coment'),
    path('',views.inicio, name='inicio'),
    path('clases',views.clases,name='clases'),
    path('profesores',views.profesores,name='profesores'),
    path('bailarines',views.bailarines,name='bailarines'),
    path('eventocolor',views.eventocolor ,name='eventocolor'),
    path('eventomuestra',views.eventomuestra ,name='eventomuestra'),
    path('eventosolidario',views.eventosolidario,name='eventosolidario'),
    path('ingresoclases', views.ingresoclases, name='ingresoclases'),
    path('ingresoprofesores',views.ingresoprofesores,name='ingresoprofesores'),
    path('ingresoestudiantes',views.ingresoestudiantes,name='ingresoestudiantes'),
    path('ingresoevento',views.ingresoevento,name='ingresoevento'),
    path('ingresocoment',views.ingresocoment,name='ingresocoment'),
    path('profesionales',views.profesionales,name='profesionales'),
    path('formbailarines',views.formbailarines,name='formbailarines'),
    path('formingresos',views.formingresos, name='formingresos'),
    path('formprofesore',views.formprofesore,name='formprofesore'),
    path('formcursos',views.formcursos,name='formcursos'),
    path('formeventos',views.formeventos,name='formeventos'),
    path('buscar',views.buscar,name='buscar'),
    path('eventos',views.eventos,name='eventos'),
    path('eliminarprof/<int:id>',views.eliminarprof,name='eliminarprof'),
    path('eliminarcurso/<int:id>',views.eliminarcurso,name='eliminarcurso'),
    path('eliminarbailarin/<int:id>',views.eliminarbailarin,name='eliminarbailarin'),
    path('eliminoevento/<int:id>',views.eliminoevento,name='eliminoevento'),
    path('noencontrado',views.noencontrado, name='noencontrado'),
    path('editclase/<int:id>',views.editclase,name='editclase'),
    path('editclase/',views.editclase,name='editclase'),
    path('editprofe/<int:id>',views.editprofe,name='editprofe'),
    path('editprofe/',views.editprofe,name='editprofe'),
    path('editevento/<int:id>',views.editevento, name='editevento'),
    path('editevento/',views.editevento, name='editevento'),
    path('editalumno/<int:id>',views.editalumno,name='editalumno'),
    path('editalumno/',views.editalumno,name='editalumno'),
    path('altas',views.altas,name='altas'),
    path('paginas',views.paginas,name='paginas'),
    path('aboutme',views.aboutme,name='aboutme'),
    path('modif_perfil',views.modif_perfil,name='modif_perfil'),
    path('registro/',include('registro.urls')),
    # path('',,name=''),
    ]